services:

  backend:
    build:
      context: ./todo-back
    env_file:
      - .env
    ports:
      - "${PORT_BACK:-8889}:8889"
    environment:
      - MONGO_STRING=${MONGO_STRING}
      - PORT_BACK=${PORT_BACK:-8889}
    networks:
      - app-network

  frontend:
    build:
      context: ./todo-front
      args:
        - VITE_API_URL=${VITE_API_URL:-}
    ports:
      - "${PORT_FRONT:-80}:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge